# Gazebo Sim to ROS 2 bridges for the RL-compatible TurtleBot model.
- ros_topic_name: "/turtlebot3/joint_states"
  gz_topic_name: "/turtlebot3/joint_states"
  ros_type_name: "sensor_msgs/msg/JointState"
  gz_type_name: "gz.msgs.Model"
  direction: GZ_TO_ROS

- ros_topic_name: "/turtlebot3/odometry"
  gz_topic_name: "/turtlebot3/odometry"
  ros_type_name: "nav_msgs/msg/Odometry"
  gz_type_name: "gz.msgs.Odometry"
  direction: GZ_TO_ROS

- ros_topic_name: "/turtlebot3/tf"
  gz_topic_name: "/turtlebot3/tf"
  ros_type_name: "tf2_msgs/msg/TFMessage"
  gz_type_name: "gz.msgs.Pose_V"
  direction: GZ_TO_ROS

- ros_topic_name: "/turtlebot3/cmd_vel"
  gz_topic_name: "/turtlebot3/cmd_vel"
  ros_type_name: "geometry_msgs/msg/Twist"
  gz_type_name: "gz.msgs.Twist"
  direction: ROS_TO_GZ

- ros_topic_name: "/turtlebot3/imu"
  gz_topic_name: "/turtlebot3/imu"
  ros_type_name: "sensor_msgs/msg/Imu"
  gz_type_name: "gz.msgs.IMU"
  direction: GZ_TO_ROS

- ros_topic_name: "/turtlebot3/scan"
  gz_topic_name: "/turtlebot3/scan"
  ros_type_name: "sensor_msgs/msg/LaserScan"
  gz_type_name: "gz.msgs.LaserScan"
  direction: GZ_TO_ROS

- ros_topic_name: "/turtlebot3/camera/camera_info"
  gz_topic_name: "/turtlebot3/camera/camera_info"
  ros_type_name: "sensor_msgs/msg/CameraInfo"
  gz_type_name: "gz.msgs.CameraInfo"
  direction: GZ_TO_ROS
